import { dirname } from "node:path";
import type { TopologySpec } from "./topology-schema";

export function generatePtBuilderScript(spec: TopologySpec, outPath: string, iosConfig: string): string {
  const lines: string[] = [
    "/* Generated by md2pkt. Keep this script as a deployment artifact for reproducible Packet Tracer builds. */",
    "function md2pktCall(name, args) {",
    "  if (typeof globalThis[name] !== 'function') { throw new Error('PTBuilder function missing: ' + name); }",
    "  return globalThis[name].apply(null, args);",
    "}",
    "function md2pktTrySave(path) {",
    "  var candidates = ['saveAs', 'saveFileAs', 'savePacketTracerFile'];",
    "  for (var i = 0; i < candidates.length; i++) {",
    "    if (typeof globalThis[candidates[i]] === 'function') { globalThis[candidates[i]](path); return true; }",
    "  }",
    "  throw new Error('No Packet Tracer save function is available in this PTBuilder environment.');",
    "}",
    `/* Output directory: ${escapeForComment(dirname(outPath))} */`
  ];

  for (const device of spec.devices) {
    lines.push(`md2pktCall("addDevice", ${jsonArgs([device.id, device.model, device.x, device.y])});`);
  }

  for (const link of spec.links) {
    lines.push(`md2pktCall("addLink", ${jsonArgs([link.from, link.fromPort, link.to, link.toPort, link.cable])});`);
  }

  for (const host of spec.hostAddresses) {
    lines.push(`md2pktCall("configurePcIp", ${jsonArgs([host.device, host.ip, host.mask, host.gateway, host.dns])});`);
  }

  const configBlocks = splitIosConfig(iosConfig);
  for (const block of configBlocks) {
    lines.push(`md2pktCall("configureIosDevice", ${jsonArgs([block.device, block.config])});`);
  }

  lines.push(`md2pktTrySave(${JSON.stringify(outPath)});`);
  return `${lines.join("\n")}\n`;
}

function splitIosConfig(iosConfig: string): Array<{ device: string; config: string }> {
  return iosConfig
    .split(/\n{2,}/)
    .map(block => {
      const device = /^!\s+(\S+)/.exec(block)?.[1];
      return device ? { device, config: block } : undefined;
    })
    .filter((block): block is { device: string; config: string } => Boolean(block));
}

function jsonArgs(args: unknown[]): string {
  return JSON.stringify(args);
}

function escapeForComment(value: string): string {
  return value.replace(/\*\//g, "* /");
}
